import uniqueId from "lodash/uniqueId";

export const data = [
  {
    id: uniqueId(),
    title: 'Сказочное заморское яство',
    name: 'Нямушка',
    taste: 'с фуа-гра',
    amount: '10 порций',
    gift: 'мышь в подарок',
    weight: '0,5',
    unit: 'кг',
    bottomTextDefault: 'Чего сидишь? Порадуй котэ,',
    bottomTextSelected: 'Печень утки разварная с артишоками.',
    bottomTextDisabled: 'Печалька, с фуа-гра закончился.',
    action: 'купи.',
    isDisabled: false,
  },
  {
    id: uniqueId(),
    title: 'Сказочное заморское яство',
    name: 'Нямушка',
    taste: 'с рыбой',
    amount: '40 порций',
    gift: '2 мыши в подарок',
    weight: '2',
    unit: 'кг',
    bottomTextDefault: 'Чего сидишь? Порадуй котэ,',
    bottomTextSelected: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
    bottomTextDisabled: 'Печалька, с рыбой закончился.',
    action: 'купи.',
    isDisabled: false,
  },
  {
    id: uniqueId(),
    title: 'Сказочное заморское яство',
    name: 'Нямушка',
    taste: 'с курой',
    amount: '100 порций',
    gift: '5 мышей в подарок',
    isCustomerHappy: 'заказчик доволен',
    weight: '5',
    unit: 'кг',
    bottomTextDefault: 'Чего сидишь? Порадуй котэ,',
    bottomTextSelected: 'Филе из цыплят с трюфелями в бульоне.',
    bottomTextDisabled: 'Печалька, с курой закончился.',
    action: 'купи.',
    isDisabled: true,
  },
];